FROM node:lts-alpine
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", ".eslintrc*", ".eslintignore*", "./"]
RUN npm install --developement --silent && mv node_modules ../
COPY . .
EXPOSE 3000
