version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
  nginx:
    image: nginx
    environment:
      PROXY_IP: http://signumlbri:3000/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template
      - ./certs/domain.crt:/etc/nginx/ssl/cert.crt
      - ./certs/domain.key:/etc/nginx/ssl/cert.key
  signumlbri:
    image: signumlbri:debug
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    environment:

      NODE_ENV: development
      MONGODB_URI_LOCAL: mongodb://mongo:27017/
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "run", "watch-debug"]
