version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
  signumlbri:
    image: signumlbri
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SESSION_SECRET: "A"
      MAIL_HOST:
      MAIL_USER:
      MAIL_SHOWMAIL:
      MAIL_PASSWORD:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/
    ports:
      - 3000:3000
